### ISSUE TITLE
We need a hero

### ISSUE THREAD

**Issue by brancusi** [auth0-community/auth0-ember-simple-auth#25]
We need a [hero](https://www.youtube.com/watch?v=mA4W1Ayd1jE) to write some tests for this addon.

Open to suggestions and PRs.

**Comment by artburkart** [comment]
Hopefully [this is a start](https://github.com/auth0/auth0-ember-simple-auth/pull/27)? I can keep adding more as I figure out more of the library.

**Comment by brancusi** [comment]
Awesome, thank you for getting this started!

**Comment by seawatts** [comment]
Hey, I have actually started my own addon for this because we needed to get the ball rolling and use the new features of auth0. See:
https://github.com/seawatts/ember-simple-auth-auth0

**Comment by artburkart** [comment]
My apologies, I'd completely forgotten about this project.

**Comment by beardaway** [comment]
Hey @seawatts , @brancusi and @artburkart ! Sorry for such delay in answering. We're currently working on creating a sustainable OSS ecosystem inside our auth0-community repos so that they can provide all the developers contributing with better experience.

Sorry for that inconvenience one more time, doing our best to provide you with better experience in near future!
