### ISSUE TITLE
passwordless possible?

### ISSUE THREAD

**Issue by dbinetti** [auth0-community/auth0-ember-simple-auth#52]
Is this library compatible with passwordless?  i might be missing something in the code, but i can't see any references to it.

**Comment by fredguth** [comment]
@dbinetti Yes, it is. You can access VerifyCode, etc from it.

**Comment by deepflame** [comment]
any possibility to get an answer on that?

Guess we need to write our own wrapper, right?

**Comment by fredguth** [comment]
No, this is not for passwordless login.  But you may use it as an example to create your on authorizer for ember-simple-auth, using passwordless login.

**Comment by beardaway** [comment]
Hey @dbinetti  and @deepflame  ! Sorry for such delay in answering. We're currently working on creating a sustainable OSS ecosystem inside our auth0-community repos so that they can provide all the developers contributing with better experience.

Your question is probably not a thing anymore but @fredguth was right. Sorry for that inconvenience one more time doing our best to provide you with better experience in near future!
