### ISSUE TITLE
Auth0-js integration outside of lock

### ISSUE THREAD

**Issue by andyo729** [auth0-community/auth0-ember-simple-auth#55]
I have been working on an authenicator that uses the auth0-js library instead of lock. It was inspired by this addon, so it might be nice to have them in the same repo. I wanted to check to see if that is something you would be interested in before I get it fully integrated into this repo.

Otherwise, I'll just publish it as a standalone addon with references to this addon.

Thanks!

**Comment by beardaway** [comment]
Hey @andyo729 ! Sorry for such delay in answering. We're currently working on creating a sustainable OSS ecosystem inside our auth0-community repos so that they can provide all the developers contributing with better experience.

In terms of your addon (it's probably not a thing anymore but), for any future reference it's better to publish it as standalone and reference. Thanks a lot and sorry for the inconvenience!
